### ISSUE TITLE
ppl changes double arithmetic

### ISSUE THREAD

**Issue by saraedum** [conda-forge/ppl-feedstock#8]
SageMath builds PPL with `--disable-fpmath`, https://github.com/sagemath/sage/blob/develop/build/pkgs/ppl/spkg-install.in#L7. The reason for this is, I guess, that PPL changes some aspects of double arithmetic. Namely, in `initializer.hh` some generic initialization happens through a
```cpp
static Parma_Polyhedra_Library::Init Parma_Polyhedra_Library_initializer;
```

This initialization then for example calls `fpu_set_rounding_direction`. This has strange side effects:

```py
>>> import cppyy
>>> from decimal import Decimal
>>> w = 0.0000000000000001224646799147353207173764029458396604625692124677580063796256126806838437914848327636718750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
>>> Decimal(w*w)
Decimal('1.499759782661857607835623101543336284205351508247989035259582954379199794559075005657977630590949047473259270191192626953125E-32')
>>> cppyy.load_library('libppl')
True
>>> cppyy.include('ppl.hh')
True
>>> Decimal(w*w)
Decimal('1.499759782661857881526729414984170448996285744559733425935743477136186465861474202882798467673097775332280434668064117431640625E-32')
```

Should we build a variant of ppl with `--disable-fpmath` here as well? @isuruf

**Comment by isuruf** [comment]
I think we should just disable it and have it be the default.

**Comment by slel** [comment]
Speaking of rounding direction, help is welcome with:

- [Sage Trac ticket 26956: bug in comparisons between AA and RealField with RNDU rounding](https://trac.sagemath.org/ticket/26956)
- [Sage Trac ticket 29957: Bug in ContinuedFraction rounding](https://trac.sagemath.org/ticket/29957)

in case you have any ideas.
